### ISSUE TITLE
Doesn't work on Windows 10... Yet...

### ISSUE THREAD

**Issue by olliegilbey** [bradfeehan/Dvorak-QWERTY-Ctrl#1]

**Comment by bradfeehan** [comment]
I don't personally have any plans yet to use Windows 10, but when I do I'm sure to need it. I'd welcome a pull request.

**Comment by crwang** [comment]
It worked for me on Windows 10.

**Comment by crwang** [comment]
Thanks @bradfeehan this is very helpful to my everyday life!

**Comment by ym1234** [comment]
Works for me (On all versions of windows 10)

**Comment by bradfeehan** [comment]
Thanks everyone!

**Comment by czhang03** [comment]
I am on Windows 10 1909, It installed just fine, but I cannot find it in my language switch (win+space).

Anyone know what could be the potential cause of this issue?

Edit: solved by restarting the system.
