### ISSUE TITLE
SGCAP Qwerty Option

### ISSUE THREAD

**Issue by 7fe** [bradfeehan/Dvorak-QWERTY-Ctrl#4]
http://kbdlayout.info/features/SGCAPS

SCAP allows you to switch to essentially different keys for Windows and is used in several layouts.

Would you consider doing this for this layout?

I was thinking press capslock switch to Qwerty press it again switch back.

**Comment by bradfeehan** [comment]
I think (and please correct me if I'm wrong) that this would be a different use-case than the existing layout here. I created this layout for the specific purpose of matching how things work on macOS, so I would prefer not to deviate from that design.

**Comment by 7fe** [comment]
hmm okay if this is supposed to be a macOS copy consider this maybe with AltGr.

https://commons.wikimedia.org/wiki/File:Special-Characters-Mac.png

I for one have to switch between 3 layouts now.

 1) qwerty other users
 2) pure Dvorak(use with my laptop with out mouse)
 3) Dvorak with qwerty shortcuts

not to sidetrack you but SGCAP would cut this to two which I will do it myself I guess.
